fixed returning a doctype declaration when the markdownText is null. …
KnpLabs/KnpMarkdownBundle pull request #86
Opened 2016-07-04 11:26 UTC by bartmcleod

…It should return an empty string when null is passed in. At least: that seems the sensible thing to do.

2017-06-03 11:09 UTC, Nek- requested changes

2017-06-03 11:09 UTC, Nek- commented on .gitignore
> +.idea
❌ you should add this in your global gitignore but should not be in this oss project.

2017-06-03 11:09 UTC, Nek- commented on Parser/ParserManager.php
> +            return '';
otherwise 👍 on this

2022-02-07 14:40 UTC, weaverryan commented
Closing as this library has been abandoned for Twig's official Markdown support.

Cheers!

2022-02-07 14:40 UTC, closed without merging